#!/bin/bash
#Count line number of a file.
git status -s | grep -v '??' &> /dev/null && {
	echo -e "\n\n \E[1;31m ${dir}\E[0m"
	git branch -vvra
	git status -s | grep -v '??'
	let count_changed=${count_changed}+1
}

echo -ne "${count_changed} have changes, "