#!/bin/bash
#Count line number of a file.
exec 10<&0
exec < $1
in=$1
file="example.txt"
let count=0
while read LINE
do
    ((count++))
    echo $LINE > $file
    if [ $? -ne 0 ] 
     then echo "Error to read file:  ${file};"
    fi
done

echo "Total Lines : $count"
exec 0<&10 10<&-