#!/bin/bash
@echo on
#Save starting path
start=$(pwd)
#Move to folder you want to backup
cd $1
#dump the desired database
mysqldump -u $2 -ptoor $3 > $3.sql
sudo mkdir SQL
sudo mv $3.sql SQL/
#go back to starting dir
cd $start
today=`date '+%Y_%m_%d'`;
sudo zip -r $1_$today $1
cd $1
sudo rm -rf SQL
