#!/bin/bash

apt-get update
apt-get upgrade
apt-get install git
apt-get install apache2
apt-get install  php libapache2-mod-php php-mcrypt
apt-get install mysql-server libapache2-mod-auth-mysql php-mysql
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin
service apache2 restart
echo "<?php phpinfo(); ?>" >> /var/www/html/phpinfo.php