#!/bin/bash

apt-get update
apt-get upgrade
apt-get install git
apt-get install apache2
apt-get install  php5 libapache2-mod-php5 php5-mcrypt
apt-get install mysql-server libapache2-mod-auth-mysql php5-mysql
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin
service apache2 restart
echo "<?php phpinfo(); ?>" >> /var/www/html/phpinfo.php