#!/bin/bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
sudo apt-get install apache2
sudo apt-get install  php5 libapache2-mod-php5 php5-mcrypt php-mbstring
sudo apt-get install php-dom php-curl php5-fpm php5-cli
sudo apt-get install mysql-server libapache2-mod-auth-mysql php5-mysql
sudo mysql_install_db
sudo mysql_secure_installation
sudo apt-get install phpmyadmin
sudo service apache2 restart
echo "<?php phpinfo(); ?>" >> /var/www/html/phpinfo.php
