#!/bin/bash
apt-get update
apt-get install git
apt-get install sshpass
git clone https://github.com/tier5/ShellScripts
cd ShellScripts
git fetch
git checkout ubuntu
export PATH=$PATH:.
cd ~
sudo echo " PATH=$PATH:~/ShellScripts" >> ~/.bashrc
source ~/.bashrc
