#!/bin/bash
#Author: Santanu
#Descripttion: This application will create and setup a new sailsjs project

cd /var/www/html
sudo npm -g install sails;
echo "Please enter the Project name";
read project_name;
sails new $project_name;
cd /var/www/html/$project_name;
sails lift;

