#!/bin/bash
#Author: Santanu
#Descripttion: This application will check all your modified files and untracked files and will commit your code. And also it'll merge your code to remote branch and push your code to remote branch.

#Push all the latest code to remote repository
function pullandpush {
	echo -n "$(tput setaf 1) Do you to want push this branch to remote branch? Press y/n :$(tput sgr0)"
    read yn
    case $yn in
        [Yy]* ) 
			echo -n "$(tput setaf 1)Do you wanna merge all the commit message together in one?Press Yes to continue by adding all the files? Press y/n :$(tput sgr0)" 
	        read yn
	        case $yn in
		        [Yy]* ) 
					echo -n "$(tput setaf 1)Here is your commit log";
					git log --oneline;
					echo -n "$(tput setaf 1)Please copy and paste the commit head that you want to make the commit merger head :$(tput sgr0)";
					read input_mergerhead;
					git reset --soft $input_mergerhead;
					git commit --amend;
					git pull origin $current_branch_name;
					git push origin $current_branch_name;
					echo -n '$(tput setaf 1)Thanks for using this application!!'
					exit
					;;
		        [Nn]* ) 
					git pull origin $current_branch_name;
					git push origin $current_branch_name;
					echo -n '$(tput setaf 1)Thanks for using this application!!'
					exit
					;;
		        * )	echo -n '$(tput setaf 1)Please answer yes or no.';;
		    esac
		    ;;
        [Nn]* ) 
			echo '$(tput setaf 1)Thanks for using this application!!'; 
			exit
			;;
        * ) echo '$(tput setaf 1)Please answer yes or no.';;
    esac
}

#After merge, pull, push checkout to new branch
function checkouttoanotherbranch {
	echo -n "$(tput setaf 1)Do you to checkout to another branch? Press y/n : $(tput sgr0)"
	read yn
    case $yn in
        [Yy]* ) echo "$(tput setaf 1)Please enter the branch name";
                read input_variable;
				git checkout $input_variable;
                ;;
		
        [Nn]* )
				maincontrolmethod
                ;;
        * ) echo "$(tput setaf 1)Please answer yes or no.";;
    esac
}


#This method is for after merging two branch and push the code to remote branch after pulling the latest
function mergebranchandpush {
	echo -n "$(tput setaf 1)Do you to want merge this branch to another branch? Press y/n : $(tput sgr0)"
    read yn
    case $yn in
        [Yy]* )
			merger
			exit;;
        [Nn]* ) 
			pullandpush
			exit
			;;
        * ) echo '$(tput setaf 1)Please answer yes or no.';;
    esac
}

#This method will merge two branch
function merger {
	echo -n "$(tput setaf 1)Please enter the branch name : $(tput sgr0)";
    read input_new_branch;
	current_branch_name=$(git symbolic-ref -q HEAD);
	echo $current_branch_name;
    git merge $input_new_branch;
    checkouttoanotherbranch
}



#This is the main body of our main controller method
function maincontrolmethod {
	branch_name=$(git symbolic-ref -q HEAD);
	echo $branch_name;
	git status -s | grep -v '??' &> /dev/null && {
		let count_changed=${count_changed}+1
	}
	if [ -z $count_changed ]
	    then echo -n "$(tput setaf 1)Your Branch is already up-to-date! Nothing to Commit or Push"
	    mergebranchandpush
	else
		while true; do
		    echo -n "$(tput setaf 1)Some untracked files are there. Press Yes to continue by adding all the files? Press y/n : $(tput sgr0)"
		    read yn
		    case $yn in
        		[Yy]* )
		    		git add -A .
		    		echo -n "$(tput setaf 1)Please enter the commit message : $(tput sgr0)";
					read input_message
					git commit -m "$input_message";
					mergebranchandpush
					;;
				[Nn]* ) 
					echo -n '$(tput setaf 1)Remove all files or stash them? : $(tput sgr0)'
			    	read yn
			    	case $yn in
						[Yy]* )
							sudo git stash
							exit
							;;
						[Nn]* ) 
							echo "$(tput setaf 1)Sorry we can not proceed further!"
							exit
							;;
					    * ) 
							echo '$(tput setaf 1)Please answer yes or no. Press y for Yes and n for No.';;
					esac
					;;
			    * ) 
					echo '$(tput setaf 1)Please answer yes or no. Press y for Yes and n for No.';;
	    	esac
	    done
	fi
}

# This is the start point of scripts main method 
while true; do
	echo "$(tput setaf 1)Welcome to our application.";
	echo "$(tput setaf 1)Please provide full path for your project folder. :$(tput sgr0)";
    read input__folder_path
    cd $input__folder_path
    echo -n "$(tput setaf 1)Here is your list of all branches.";
    git branch
    maincontrolmethod
done
