#!/bin/bash
sudo mkdir /var/www/$1
cd /var/www/$1
sudo git init


sudo cat <<EOF > /var/www/$1/index.html
$1 site is running

EOF


sudo cat <<EOF > /etc/apache2/sites-available/$1.conf
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
        DocumentRoot /var/www/$1
<Directory /var/www/$1>
        AllowOverride All
</Directory>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF


