#!/bin/bash
sudo mkdir /var/www/$1
cd /var/www/$1
sudo git init

if [ -n "$2" ]
then
	git remote add origin $2
	git fetch
	if [ -n "$3" ]
	then
	git checkout $3
	git pull origin $3
	else
	git checkout master
	git pull origin master
	fi
fi


sudo cat <<EOF > /etc/apache2/sites-available/$1.conf
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
        DocumentRoot /var/www/$1
<Directory /var/www/$1>
        AllowOverride All
</Directory>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF


