#!/bin/bash

sudo apt-get install -y virtualbox	
sudo apt-get install -y vagrant
#sudo vagrant box add precise32 http://files.vagrantup.com/precise32.box
sudo vagrant box add precise64 http://files.vagrantup.com/precise64.box


